#!/usr/bin/env python

"""This Program Start Kagisys System."""

import threading
import os


def main():
    """Main."""
    # run nfc lock
    th_nfc_lock = threading.Thread(target=start_nef_lock, name="nfc_lock", args=())
    th_nfc_lock.start()


def start_nef_lock():
    """Start NFC Lock Sysytem."""
    # Move directry
    path = "/home/pi/project/kagisys_logic/nfc_lock/"
    os.chdir(path)
    os.system("sudo python2 nfc_lock.py")


if __name__ == '__main__':
    main()
